### ISSUE TITLE
How to use my own model?

### ISSUE THREAD

**Issue by Nuralill** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#12]
是否可以使用自己在pytorch faster-rcnn上训练得出的权重模型转onnx呢？具体需要怎么操作呢？谢谢！

**Comment by thb1314** [comment]
@Nuralill 可以采用torchvision上的faster-rcnn模型，然后训练脚本需要自己写一下。

**Comment by Nuralill** [comment]
那就是只支持resnet50吧？
