### ISSUE TITLE
请问批量预测只返回第一张图片的结果，怎么解决呢？

### ISSUE THREAD

**Issue by jacke121** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#14]
大佬您好，我把这个sdk调试通过，能检测，batch_size为2时，返回检测结果都是第一张图片的，请问这个怎么解决呀？

**Comment by thb1314** [comment]
@jacke121 很感谢你能关注这项工作，目前确实仅支持batch_size=1，batch_size>1的逻辑还未完善，期待咱们可以一起解决这个问题。
