### ISSUE TITLE
原则1和2

### ISSUE THREAD

**Issue by shining-love** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#15]
大佬你好，我看你说的原则1和2：
原则1：reshape操作第一个值为-1，即设置为batch size大小不固定

原则2：针对一些tensorrt不友好的算子比如：原地赋值、nonzero算子，equal算子等尽可能以另外方式等价替代或者舍弃

分别对应您工程中的代码在哪一步（或者说是在哪里做了以上两个原则）呢？

**Comment by thb1314** [comment]
@shining-love 体现在对torchvision官方包的修改当中

**Comment by shining-love** [comment]
> 

额，麻烦追乐大佬可以具体对应修改的哪句代码么？

**Comment by shining-love** [comment]
> 额，麻烦追乐大佬可以具体对应修改的哪句代码么？

额，麻烦追乐大佬可以具体对应修改的哪句代码么？

**Comment by shining-love** [comment]
> @shining-love 体现在对torchvision官方包的修改当中

额，麻烦追乐大佬可以具体对应修改的哪句代码么？

**Comment by thb1314** [comment]
@shining-love 请稍等，今天我给你看下
