### ISSUE TITLE
预测框不一致

### ISSUE THREAD

**Issue by 123-Zhao** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#18]
你好，在onnx转trt之后进行检测，得到的结果与onnx的预测结果不一致(置信度较低，有一些框未预测出)，请问除了阈值、参数这些，还可能是那些地方需要修改呢

**Comment by thb1314** [comment]
> 你好，在onnx转trt之后进行检测，得到的结果与onnx的预测结果不一致(置信度较低，有一些框未预测出)，请问除了阈值、参数这些，还可能是那些地方需要修改呢

只能从rpn开始debug，rpn那里我对其过没问题。本项目自带的nms与onnx的nms有一些差别

**Comment by thb1314** [comment]
> 你好，在onnx转trt之后进行检测，得到的结果与onnx的预测结果不一致(置信度较低，有一些框未预测出)，请问除了阈值、参数这些，还可能是那些地方需要修改呢

推荐使用FastNMS插件

**Comment by 123-Zhao** [comment]
> 

请问预处理部分有做其他处理吗，原faster rcnn中是PIL方式读取的，我在rpn_nms_kernel输出的框与pred_onnx["rpn_boxes"]对比是不一致的

**Comment by 123-Zhao** [comment]
> > 
> 
> 请问预处理部分有做其他处理吗，原faster rcnn中是PIL方式读取的，我在rpn_nms_kernel输出的框与pred_onnx["rpn_boxes"]对比是不一致的



> > 你好，在onnx转trt之后进行检测，得到的结果与onnx的预测结果不一致(置信度较低，有一些框未预测出)，请问除了阈值、参数这些，还可能是那些地方需要修改呢
> 
> 只能从rpn开始debug，rpn那里我对其过没问题。本项目自带的nms与onnx的nms有一些差别

请问预处理部分有做其他处理吗，原faster rcnn中是PIL方式读取的，我在rpn_nms_kernel输出的框与pred_onnx["rpn_boxes"]对比是不一致的

**Comment by thb1314** [comment]
> rpn_nms_kernel

没有任何处理，不一致原因是nms算子没有对齐

**Comment by thb1314** [comment]
@123-Zhao

**Comment by thb1314** [comment]
@123-Zhao
我们推出了当前版本的升级，支持训练、动态batch、fp16且精度与onnx对齐，欢迎star
https://github.com/thb1314/maskrcnn-tensorrt
