### ISSUE TITLE
50

### ISSUE THREAD

**Issue by Chengcheng1998727** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#19]
您好，我在使用您的代码时出现了问题:
我将第4层改为了空洞卷积，其feature map由25*25变为了50*50，结果发现在检测大尺寸目标的时候，没有检测框，于是我将sptical_scales的1/32，调整为1/16，此时能够检测出大尺寸目标，但是预测框被缩小了一部分。同时，我在第4层特征图改为空洞卷积的基础上，将ASPP结构接在了第4层，此时也没有大尺寸目标的预测框，并且我将sptical_scales的1/32，调整为1/16也同样没有预测框。
我想问一下，faster rcnn.cpp文件中的RoiAlignImpl_Float()方法是跟python阶段的roialign方法是一样的吗，有没有差距呢

**Comment by thb1314** [comment]
@Chengcheng1998727 一样的
我们推出了当前版本的升级，支持训练、动态batch、fp16且精度与onnx对齐，欢迎star
https://github.com/thb1314/maskrcnn-tensorrt
