### ISSUE TITLE
还是关于fasterrcnn问题，

### ISSUE THREAD

**Issue by wangzhenlin123** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#3]
已start，还是关于fasterrcnn问题，方便留个联系方式吗

**Comment by thb1314** [comment]
> 已start，还是关于fasterrcnn问题，方便留个联系方式吗

这里没有私信功能，你可以在手写ai群里找“追乐”，也可以在这里描述问题都可以

**Comment by thb1314** [comment]
没有详细问题，关闭
