### ISSUE TITLE
x07reduce question

### ISSUE THREAD

**Issue by skylake-L** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#5]
运行x07.py的时候遇到nodes in a graph must be topologically sorted,howerver input 'feature_0' of node : 
name: RoiAlign_51 OpType: RoiAlign is not output of any previous nodes.

老哥如何解决

**Comment by thb1314** [comment]
感觉你没有按照顺序执行所有问以x为开头的文件，建议一个一个执行。不要跳级

**Comment by thb1314** [comment]
> 运行x07.py的时候遇到nodes in a graph must be topologically sorted,howerver input 'feature_0' of node : name: RoiAlign_51 OpType: RoiAlign is not output of any previous nodes.
> 
> 老哥如何解决

感觉你没有按照顺序执行所有问以x为开头的文件，建议一个一个执行。不要跳级

**Comment by skylake-L** [comment]
我按照顺序执行了依然发生错误，torch 1.7.0+cu110 torchvision 0.8.1+cu110 onnx 1.10.2 onnx-simplifier 0.3.6
运行x01 发生两个warning error; 运行x02发生三个warning does not match; 后面也报了一些warning不知道什么原因

**Comment by thb1314** [comment]
> 我按照顺序执行了依然发生错误，torch 1.7.0+cu110 torchvision 0.8.1+cu110 onnx 1.10.2 onnx-simplifier 0.3.6 运行x01 发生两个warning error; 运行x02发生三个warning does not match; 后面也报了一些warning不知道什么原因

warning是正常的，你可以先看下说明，我更新了下，看看是不是你生成onnx算子名字与我写的不一样。

**Comment by skylake-L** [comment]
> > 我按照顺序执行了依然发生错误，torch 1.7.0+cu110 torchvision 0.8.1+cu110 onnx 1.10.2 onnx-simplifier 0.3.6 运行x01 发生两个warning error; 运行x02发生三个warning does not match; 后面也报了一些warning不知道什么原因
> 
> warning是正常的，你可以先看下说明，我更新了下，看看是不是你生成onnx算子名字与我写的不一样。

非常感谢，我看了自己的onnx确实名字不一致，但是我用的模型也是官方的fasterrcnn不知道为啥。
之后我在执行x08的时候遇到了merging shape info for output 'scores' source:{} target:{N,90}.Failing back to lenient merge.我猜想是不是模型类别的原因，你的90这个参数表示什么。

**Comment by thb1314** [comment]
> > > 我按照顺序执行了依然发生错误，torch 1.7.0+cu110 torchvision 0.8.1+cu110 onnx 1.10.2 onnx-simplifier 0.3.6 运行x01 发生两个warning error; 运行x02发生三个warning does not match; 后面也报了一些warning不知道什么原因
> > 
> > 
> > warning是正常的，你可以先看下说明，我更新了下，看看是不是你生成onnx算子名字与我写的不一样。
> 
> 非常感谢，我看了自己的onnx确实名字不一致，但是我用的模型也是官方的fasterrcnn不知道为啥。 之后我在执行x08的时候遇到了merging shape info for output 'scores' source:{} target:{N,90}.Failing back to lenient merge.我猜想是不是模型类别的原因，你的90这个参数表示什么。

N,90中的90表示coco类别，具体可以看tensorrt中里app_fasterrcnn
这个repo里的fasterrcnn是基于官方torchvision里面修改的

**Comment by 123-Zhao** [comment]
> > 运行x07.py的时候遇到nodes in a graph must be topologically sorted,howerver input 'feature_0' of node : name: RoiAlign_51 OpType: RoiAlign is not output of any previous nodes.
> > 老哥如何解决
> 
> 感觉你没有按照顺序执行所有问以x为开头的文件，建议一个一个执行。不要跳级
请问大佬，怎么按照顺序执行了还是出现这个错误啊
