### ISSUE TITLE
onnx -trt？

### ISSUE THREAD

**Issue by henbucuoshanghai** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#6]
训练完pth转onnx后转trt？

**Comment by thb1314** [comment]
对，这个repo只做了onnx后转trt，主要是对onnx做切割处理，分成两个onnx，分别为header部分和rpn部分，然后分别转trt。
训练部分不涉及。
这个repo提取自torchvision官方的FasterRCNN实现，原理上是可以采用torchvision的官方代码训练，然后将pth导入到我更改的这个repo中的模型中导出onnx，然后执行后面的onnx裁剪步骤。

**Comment by thb1314** [comment]
暂时关闭，如果其他人有类似问题，解答可供参考。
