### ISSUE TITLE
关于使用该方法部署maskrcnn

### ISSUE THREAD

**Issue by Mrwangxin1998** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roialign#8]
请问可以使用这种方法部署torchvision下的maskrcnn么？需要修改哪些内容，如果我只需要目标不求mask的话，可以直接用么

**Comment by thb1314** [comment]
已在微信群中解答，这里说下思路：
熟悉这个repo的运行原理，然后自己从torchvision中提取一份或者自己找一份其他的maskrcnn的源码，保证可以生成较为简洁的onnx。
接着采取与本repo相同的原理，将onnx分割。
